version: 2

models:
    - name: fact_orders
      description: "Tabela de fatos"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_customers
      description: "A starter dbt model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_products
      description: "A starter dbt model"
      columns:
          - name: product_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_shippers
      description: "A starter dbt model"
      columns:
          - name: shipper_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_suppliers
      description: "A starter dbt model"
      columns:
          - name: supplier_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: fact_order_details
      description: "Tabela de fatos"
